### PR TITLE
5 friends page

### PR DESCRIPTION
**Pull request by brandhawa99**
Basic design of friends page

### CODE REVIEW

**Review by rdhillon1016 — COMMENTED** [review]
Looks good.

Needs an input field somewhere so users can send out friend requests (can separate this out into another issue if you want).

Friends component looks good on mobile view. On the wider views you can probably have 2 or 3 columns instead of 1 column to use the space better.

Also the "Your friends" container and "Friend requests" container look kind of weird with respect to each other (the text isn't centered the same way and the font size is different). When Friend requests are expanded it's not a big deal but when it's not it looks weird.

**Comment by brandhawa99** [comment]
> Looks good.
> 
> Needs an input field somewhere so users can send out friend requests (can separate this out into another issue if you want).
> 
> Friends component looks good on mobile view. On the wider views you can probably have 2 or 3 columns instead of 1 column to use the space better.
> 
> Also the "Your friends" container and "Friend requests" container look kind of weird with respect to each other (the text isn't centered the same way and the font size is different). When Friend requests are expanded it's not a big deal but when it's not it looks weird.

For the input field its going to be its own search page where it brings back users first and then aything else related to what was searched. 

We could make a search option in the friends page that then redirects to the search page.
 
I think the one user per line is okay, but I agree with changing the look of the "Your friends" and "Friend requests".

**Comment by rdhillon1016** [comment]
> > Looks good.
> > Needs an input field somewhere so users can send out friend requests (can separate this out into another issue if you want).
> > Friends component looks good on mobile view. On the wider views you can probably have 2 or 3 columns instead of 1 column to use the space better.
> > Also the "Your friends" container and "Friend requests" container look kind of weird with respect to each other (the text isn't centered the same way and the font size is different). When Friend requests are expanded it's not a big deal but when it's not it looks weird.
> 
> For the input field its going to be its own search page where it brings back users first and then anything else related to what was searched.
> 
> We could make a search option in the friends page that then redirects to the search page.
> 
> I think the one user per line is okay, but I agree with changing the look of the "Your friends" and "Friend requests".

Search functionality is not going to be easy to implement at scale. That should be a future upgrade

**Comment by brandhawa99** [comment]
> > > Looks good.
> > > Needs an input field somewhere so users can send out friend requests (can separate this out into another issue if you want).
> > > Friends component looks good on mobile view. On the wider views you can probably have 2 or 3 columns instead of 1 column to use the space better.
> > > Also the "Your friends" container and "Friend requests" container look kind of weird with respect to each other (the text isn't centered the same way and the font size is different). When Friend requests are expanded it's not a big deal but when it's not it looks weird.
> > 
> > 
> > For the input field its going to be its own search page where it brings back users first and then anything else related to what was searched.
> > We could make a search option in the friends page that then redirects to the search page.
> > I think the one user per line is okay, but I agree with changing the look of the "Your friends" and "Friend requests".
> 
> Search functionality is not going to be easy to implement at scale. That should be a future upgrade

Oh I see what you are saying. Yeah just open a new issue for that.

**Pull request merged**
